[package]
name = "red"
version = "0.1.0-alpha.3"
edition = "2021"
description = "A robust and versatile Discord bot developed using the Serenity library."
license = "GPL-3.0-only WITH Commons-Clause-1.0"
readme = "README.md"
repository = "https://github.com/Plarpoon/Red"
publish = false

[dependencies]
serenity = { version = "0.12.4", features = ["full"] }
tokio = { version = "1.43.0", features = ["full"] }
serde = "1.0.218"
toml = "0.8.20"
chrono = "0.4.39"
log = "0.4.26"
surrealdb = "2.2.1"
colored = "3.0.0"
fern = "0.7.1"
